#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# deploy.sh  —  deploy DropCloud infrastructure + Lambda code to AWS
#
# Prerequisites:
#   aws cli v2 installed + configured (aws configure)
#   node 20+ installed
#
# Usage:
#   chmod +x deploy.sh
#   ./deploy.sh [dev|prod]   (default: dev)
# ─────────────────────────────────────────────────────────────────────

set -euo pipefail

STAGE="${1:-dev}"
APP="dropcloud"
REGION="${AWS_DEFAULT_REGION:-eu-north-1}"
STACK="${APP}-stack-${STAGE}"

echo "▶ Deploying ${APP} [${STAGE}] → ${REGION}"

# ── 1. Deploy CloudFormation stack ──────────────────────────────────
echo "▶ Deploying CloudFormation stack…"
aws cloudformation deploy \
  --template-file infrastructure/cloudformation.yml \
  --stack-name "$STACK" \
  --parameter-overrides AppName="$APP" Stage="$STAGE" \
  --capabilities CAPABILITY_NAMED_IAM \
  --region "$REGION"

# ── 2. Fetch stack outputs ───────────────────────────────────────────
echo "▶ Fetching stack outputs…"

get_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

BUCKET=$(get_output BucketName)
TABLE=$(get_output TableName)
API=$(get_output ApiEndpoint)
USER_POOL=$(get_output UserPoolId)
USER_POOL_CLIENT=$(get_output UserPoolClientId)
IDENTITY_POOL=$(get_output IdentityPoolId)

echo "  Bucket:       $BUCKET"
echo "  Table:        $TABLE"
echo "  API Endpoint: $API"

# ── 3. Package + deploy Lambda functions ────────────────────────────
echo "▶ Packaging Lambda functions…"

deploy_lambda() {
  local FN_NAME="$1"
  local FN_DIR="lambda/$FN_NAME"
  local ZIP="/tmp/${FN_NAME}.zip"

  echo "  Packaging ${FN_NAME}…"
  (cd "$FN_DIR" && zip -rq "$ZIP" index.js)

  aws lambda update-function-code \
    --function-name "${APP}-${FN_NAME}-${STAGE}" \
    --zip-file "fileb://${ZIP}" \
    --region "$REGION" \
    --query 'FunctionName' \
    --output text > /dev/null

  echo "  ✓ ${FN_NAME} deployed"
}

deploy_lambda "onS3Upload"
deploy_lambda "listFiles"
deploy_lambda "getVersions"
deploy_lambda "deleteFile"

# ── 4. Write aws-exports.js ──────────────────────────────────────────
echo "▶ Writing src/aws-exports.js…"

cat > src/aws-exports.js << EOF
// Auto-generated by deploy.sh — do NOT commit this file
const awsConfig = {
  Auth: {
    Cognito: {
      userPoolId:       '${USER_POOL}',
      userPoolClientId: '${USER_POOL_CLIENT}',
      identityPoolId:   '${IDENTITY_POOL}',
      region:           '${REGION}',
    },
  },
  Storage: {
    S3: {
      bucket: '${BUCKET}',
      region: '${REGION}',
    },
  },
  API: {
    REST: {
      dropcloudApi: {
        endpoint: '${API}',
        region:   '${REGION}',
      },
    },
  },
};
export default awsConfig;
EOF

echo "▶ aws-exports.js written"

# ── 5. Build React app ───────────────────────────────────────────────
echo "▶ Building React app…"
npm ci
npm run build

echo ""
echo "✅  Deploy complete!"
echo "   Upload the /build folder to Amplify Hosting, or run:"
echo "   aws amplify start-deployment …"
echo ""
echo "   API: $API"
